### ISSUE TITLE
[Improvement] Improve values.schema.json for kbcli create command

### ISSUE THREAD

**Issue by wangyelei** [apecloud/kubeblocks-addons#1082]
List of values addon to be added:
- addons-cluster/clickhouse/
- addons-cluster/loki/
- addons-cluster/milvus/
- addons-cluster/nebula/
- addons-cluster/opensearch/
- addons-cluster/polardbx/
- addons-cluster/pulsar/
- addons-cluster/tidb/
- addons-cluster/weaviate/

**Comment by shanshanying** [comment]
https://github.com/apecloud/kubeblocks/issues/8450
