### ISSUE TITLE
[Features] support kafka 2.2.2

### ISSUE THREAD

**Issue by shuoshadow** [apecloud/kubeblocks-addons#1099]

**Comment by shanshanying** [comment]
Hi @shuoshadow 

Thansk for your interrests in KubeBlocks.

We did not plan to suppor Kafka prior 3.0. 
If you are using Kafka 2.2.2 at the moment, you may refer to our PR for Kafka 2.8 Addon and contribute one:
https://github.com/apecloud/kubeblocks-addons/pull/917
