### ISSUE TITLE
postgres的official-postgresql-cc文件借鉴的时候，报错 

### ISSUE THREAD

**Issue by binbin21avery** [apecloud/kubeblocks-addons#154]
根据addons中的office-postgresql借鉴自己写了一个addons,然后在启动集群的时候，关于validate configmap报错，
错误是： failed to validate configmap: [missing ',' in struct literal: 1127:29 expected '}', found 'EOF': 1133:2]

我是在office-postgresql这个文件的基础上进行的修改，不知道为什么创建集群的时候就一直卡在这里，

**Comment by binbin21avery** [comment]
![WX20231227-154851](https://github.com/apecloud/kubeblocks-addons/assets/38284249/b5ab7998-88f5-4c88-a8da-f7ad44cff651)
这是文件的截图，直接上传好像格式有些问题

**Comment by sophon-zt** [comment]
Pls  try this command: `cue vet xxxx.cue`？

**Comment by shanshanying** [comment]
Resolved.
