### ISSUE TITLE
[Features] Support MogDB Standalone and Replication Mode

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#172]
Support MogDB Cluster with following features:
- [x] Create Standalone, and Replication (Primary/Secondary) Cluster
- [x] FailOver/SwitchOver
- [ ] Vscale
- [x] Hscale
- [x] Volumeexpand
- [ ] Stop/Start
- [ ] Restart
- [x] Backup/Restore
- [x] Config
- [x] Monitoring

**Comment by yabinji** [comment]
针对支持的特性做以下补充：
1. 有条件的支持Vscale。默认情况下，Vscale会引发重新调度，导致主备关系出现异常。如果平台支持在线vscale，则支持vscale。
2. 不支持monitoring。
3. 支持Hscale。
