### ISSUE TITLE
[Features] Support Apache Doris

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#174]
Support Doris Cluster with following features:
- [ ] Create  Cluster
- [ ] FailOver/SwitchOver
- [ ] Vscale
- [ ] Hscale
- [ ] Volumeexpand
- [ ] Stop/Start
- [ ] Restart
- [ ] Backup/Restore
- [ ] Config
- [ ] Monitoring
- ...

**Comment by yuqun20230302** [comment]
Support Doris Cluster with following features:

- **Frontend(fe) Component:**
- [x] Create Cluster
- [x] FailOver/SwitchOver
- [ ] Vscale
- [x] Hscale
- [x] Volumeexpand
- [x] Stop/Start
- [x]  Restart
- [ ] Backup/Restore
- [x] Config
- [x] Monitoring

- **Backend(be) Component:**
- [x] Create Cluster
- [x] FailOver/SwitchOver
- [x] Vscale
- [x] Hscale
- [x] Volumeexpand
- [x] Stop/Start
- [x]  Restart
- [ ] Backup/Restore
- [x] Config
- [x] Monitoring

- **ComputeNode(cn) Component:**
- [x] Create Cluster
- [x] FailOver/SwitchOver
- [x] Vscale
- [x] Hscale
- [ ] Volumeexpand
- [x] Stop/Start
- [x]  Restart
- [ ] Backup/Restore
- [x] Config
- [x] Monitoring

**Comment by iziang** [comment]
It would be even better if screenshots of the tests for each feature could be provided.

**Comment by shanshanying** [comment]
> It would be even better if screenshots of the tests for each feature could be provided.

check the file enclosed. provided by @yuqun20230302 
[doris2.0.3-test-by-yuqun20230302.pdf](https://github.com/apecloud/kubeblocks-addons/files/13839859/doris2.0.3-test-by-yuqun20230302.pdf)
