### ISSUE TITLE
[Features] Support MariaDB Monitoring and Backup/Restore

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#209]
This is a follow-up of apecloud/kubeblocks#5381 , which should:
- [ ] support backup and restore a cluster
- [ ] support monitoring (metrics collection and dashboard)

**Comment by LiuG-lynx** [comment]
Kubernetes: v1.23.8+k3s1
KubeBlocks: 0.7.2
kbcli: 0.7.2

I'm having a problem with environment variables and paths when I build the actionset for backup, only when copying the backup file to the `DATASAFED_LOCAL_BACKEND_PATH` directory will the backup actually be backed up to the `backuprepo`, using the `DP_BACKUP_DIR` doesn't work, Is DATASAFED_LOCAL_BACKEND_PATH the correct path? am I using the playground environment and the csi-hostpath-sc storageclass  problem? @shanshanying


<img width="1365" alt="Untitled" src="https://github.com/apecloud/kubeblocks-addons/assets/29352057/11b76640-923e-49e1-ba15-e3fbcb7eba6e">

**Comment by LiuG-lynx** [comment]
```bash
/${DP_BACKUP_DIR}/${DP_BACKUP_NAME}.mbstream   //  ERROR
${DATASAFED_LOCAL_BACKEND_PATH}/${DP_BACKUP_NAME}.mbstream  // When recovering,  can get the corresponding backup file
```
