### ISSUE TITLE
[Improvement] KubeBlocks Clusters to Support Specifying the `StorageClass`

### ISSUE THREAD

**Issue by dingshun-cmss** [apecloud/kubeblocks-addons#457]
## Is your improvement request related to a problem? Please describe.
In my K8S cluster, there are several storage classes available. I would like the ability to select the specific storage class when creating KubeBlocks clusters.

## If this is a new function, please describe the motivation and goals.
N/A

## Describe the solution you'd like
Within `kblib.componentStorages`, we can enable `volumeClaimTemplates` to support specifying a storage class, while ensuring backward compatibility. 

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by shanshanying** [comment]
take care of the default behavior, when storageClassName is nil or empty.
