### ISSUE TITLE
[BUG] apecloud-mysql smartengine:The parameter does not take effect after vscale

### ISSUE THREAD

**Issue by haowen159** [apecloud/kubeblocks-addons#460]
在apecloud-mysql引擎下测试内存扩容，发现相应的参数没有受到影响。
测试流程：
1.根据配置文件，测试loose_smartengine_db_write_buffer_size有没有发生变化，渲染后，它为smartengine_db_write_buffer_size
![image](https://github.com/apecloud/kubeblocks-addons/assets/78309270/2af13ba6-c80a-42a7-987c-b9b967f6436d)
2.在测试程序中，创建了apecloud-mysql并开启smartengine配置的集群：smarte-mpkiua ，初始内存为1G，获取相应的loose_smartengine_db_write_buffer_size值，将其扩容到1.5G后，再获取该值进行对比，发现扩容前后该值没有变化
<img width="1329" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/78309270/9016bfb8-9e4a-4112-b44a-f63a6fdc54ef">
3.为了验证结果，我手动创建了内存为1G和1.5G，其余配置与测试集群相同的两个集群ape-1和ape-2，获取该值后发现它受memory大小影响
![image](https://github.com/apecloud/kubeblocks-addons/assets/78309270/cfa32e66-37db-45b9-af34-95cb11cf0f5c)
4.随后我又检查了测试集群的内存大小，并手动获取该值，发现确实存在问题：测试集群扩容成功，该值没有变化
![image](https://github.com/apecloud/kubeblocks-addons/assets/78309270/4d69baf3-1279-4aa5-8302-c8edeb950465)

![image](https://github.com/apecloud/kubeblocks-addons/assets/78309270/51acf11e-d93b-477b-a22c-f4c8980ef377)

**Comment by sophon-zt** [comment]
The rerender feature needs to be enabled on the addon to take effect.

I will update the addon.
