### ISSUE TITLE
[BUG]oracle_mysql:The parameters are not affected after VerticalScaling

### ISSUE THREAD

**Issue by haowen159** [apecloud/kubeblocks-addons#471]
**Describe the bug**
对oracle_mysql引擎下的集群进行内存扩容，max_connections参数没有发生变化
**To Reproduce**
1.查阅oracle_mysql配置文件可以得出，max_connections的值由组件内存大小决定（因为除的数是常数）
![image](https://github.com/apecloud/kubeblocks-addons/assets/78309270/ce8f8e61-5e18-447e-8204-8a1105e0a1f6)
2.在测试程序中创建该引擎下的集群，并对其进行扩容，查询对比扩容前后max_connections值，发现其没有变化
<img width="1471" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/78309270/9dcff19e-feff-4321-b667-fead0ba2b49d">
<img width="1471" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/78309270/894453a6-8285-4037-9268-29fcea8beffa">
<img width="1471" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/78309270/9fd4deff-9c61-4450-8c74-b30eeee52c9a">
3.为了验证测试结果，我又分别手动创建了与程序中扩容前后配置相同的两个集群，并对比了三者的max_connections，发现其确实与内存大小有关，但是扩容前后没有改变。
![image](https://github.com/apecloud/kubeblocks-addons/assets/78309270/79776b84-b42e-4e67-ba5a-3ff96bf6d98b)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by shanshanying** [comment]
use our `mysql addon` instead, the stable version is release 0.8 for  now.
