### ISSUE TITLE
[BUG]mysql:The parameters are not affected after VerticalScaling

### ISSUE THREAD

**Issue by haowen159** [apecloud/kubeblocks-addons#472]
**Describe the bug**
对mysql引擎下的集群进行内存扩容，max_connections参数没有发生变化
**To Reproduce**
1.查阅mysql配置文件可以得出，max_connections的值由组件内存大小决定（因为除的数是常数）
![image](https://github.com/apecloud/kubeblocks-addons/assets/78309270/fb945440-56d2-44c9-89e0-a93883c84711)
2.在测试程序中创建该引擎下的集群，并对其进行扩容，查询对比扩容前后max_connections值，发现其没有变化
<img width="1766" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/78309270/3790ea1f-79e3-4bcd-9483-5bda793df7d0">
<img width="1409" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/78309270/7088727c-4773-4d91-bbf1-3fb53c6d13ad">
<img width="1448" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/78309270/4fe264b1-897a-4778-b6d9-c45876f81b28">
3.为了验证测试结果，我又分别手动创建了与程序中扩容前后配置相同的两个集群，并对比了三者的max_connections，发现其确实与内存大小有关，但是扩容前后没有改变。
<img width="1766" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/78309270/a08e364d-3d7b-438b-8818-bb94eb69fe27">

**Comment by nayutah** [comment]
Still not works as expected when I upgrade an apecloud-mysql cluster from 1C2G to 2C8G, the max_connection remains the same.

**Comment by sophon-zt** [comment]
addon是不是没有升级？哪个环境？我看看

**Comment by nayutah** [comment]
In dev env, the problem is still there.

**Comment by sophon-zt** [comment]
The addon in the dev environment does not enabled the rerender function of vscale.  I will fix it.
