### ISSUE TITLE
How Oceanbase Hostnetwork Works？

### ISSUE THREAD

**Issue by LiuG-lynx** [apecloud/kubeblocks-addons#554]
May I ask why the oceanbase cluster needs to use a host network, and how should the IP host network be set up?

https://github.com/apecloud/kubeblocks-addons/blob/3ebf63a2c894eedfb75c8eb8e3058f5caf1efc54/addons/oceanbase-ce-cluster/values.yaml#L36

**Comment by shanshanying** [comment]
Hi @LiuG-lynx Liu

When HostNetwork is enabled, at POD level, it differs in two fields:
```yaml
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```

But for KB controller, we will manage ports allocation to avoid ports conflicts.

**Comment by LiuG-lynx** [comment]
Thank you for your answer

> Hi @LiuG-lynx Liu
> 
> When HostNetwork is enabled, at POD level, it differs in two fields:
> 
> ```yaml
>       hostNetwork: true
>       dnsPolicy: ClusterFirstWithHostNet
> ```
> 
> But for KB controller, we will manage ports allocation to avoid ports conflicts.
