### ISSUE TITLE
[Bug] Docker Hub image problem

### ISSUE THREAD

**Issue by zhubao315** [apecloud/kubeblocks-addons#677]
The docker hub image in China cannot be pulled anymore. It is recommended to set up an environment variable to switch the image address, or use an offline installation package.

**Comment by ldming** [comment]
Your request is very reasonable. Our addons provide fields to set the registry for almost all the images used. Some are unified, for example, you can set the registry for all images through image.registry. Some addons do not use the value from image.registry uniformly but use configurations from other fields instead. There might be a few cases with hardcoded values. We will review these configurations. You are also welcome to submit issues or PRs for specific addons. Thank you very much.
