### ISSUE TITLE
[Improvement] Make kafka image registry configurable

### ISSUE THREAD

**Issue by nayutah** [apecloud/kubeblocks-addons#682]
Is your improvement request related to a problem? Please describe.
hardcoded ones:
kafka/values.yaml:    repository: docker.io/bitnami/kafka
kafka/values.yaml:    repository: docker.io/bitnami/kafka-exporter
kafka/values.yaml:    repository: docker.io/bitnami/jmx-exporter
kafka/opsdefinitions/quota.yaml:              image: docker.io/bitnami/kafka:3.3.2-debian-11-r54
kafka/opsdefinitions/topic.yaml:              image: docker.io/bitnami/kafka:3.3.2-debian-11-r54
kafka/opsdefinitions/useracl.yaml:            image: docker.io/bitnami/kafka:3.3.2-debian-11-r54

**Comment by yipeng1030** [comment]
fixed in #660

**Comment by nayutah** [comment]
Some ops still has such problem:
opsdefinitions/quota.yaml:              image: docker.io/bitnami/kafka:3.3.2-debian-11-r54
opsdefinitions/quota.yaml:              imagePullPolicy: IfNotPresent
opsdefinitions/topic.yaml:              image: docker.io/bitnami/kafka:3.3.2-debian-11-r54
opsdefinitions/topic.yaml:              imagePullPolicy: IfNotPresent
opsdefinitions/useracl.yaml:            image: docker.io/bitnami/kafka:3.3.2-debian-11-r54
opsdefinitions/useracl.yaml:            imagePullPolicy: IfNotPresent
