### ISSUE TITLE
[BUG] ac-mysql addon, replace docker.io images

### ISSUE THREAD

**Issue by shanshanying** [apecloud/kubeblocks-addons#759]
1. update image registry
2. 
<img width="1365" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/111829739/647e2773-
6e1d-41b9-80f0-651eb9bb4dbd">

<img width="1335" alt="image" src="https://github.com/apecloud/kubeblocks-addons/assets/111829739/97168e52-8ac9-4bc4-9404-cb81f8e3683a">

3. disable exporter by default, in cluster

**Comment by nayutah** [comment]
@sophon-zt make oteld exporters' image registry configurable
