### ISSUE TITLE
[Improvement] addons re version

### ISSUE THREAD

**Issue by loomts** [apecloud/kubeblocks-addons#985]
![image](https://github.com/user-attachments/assets/b4e66fbc-11d2-493e-bd4a-6e7badd54779)

some add-on version used engine version,
e.g. 
milvus 2.3.2
minio 5.2.0
orchestrator 3.2.6
pika 3.5.1

it's better to make it use kb version.

**Comment by shanshanying** [comment]
orchestrator version is: 0.8. 0.9, and 3.2.6 (deprecated)
minio version is: 0.9.0, 5.2.0 (non-addon mode, deprecrated)
pika is not maintained by KB.

@loomts only milvus 2.3.2 should be considered.
